name: Default workflow

on:
    push:
        branches:
            - master
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    TERM: dumb

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: "zulu"
                    java-version: "17"
            -   name: Lint
                run: |
                    find "$(pwd -P)" -type f \
                    \( -name "*.bazel" -o -name "WORKSPACE" \) \
                    -not -path "*/buildsystem/*" \
                    -exec bazelisk run //:buildifier --config=ci -- --mode=check -v {} +
    bazel-build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Bazel build
                uses: ./.github/actions/bazel
                with:
                    bazel-command: build //...
                    cache-key: bazel-build
    bazel-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Query targets
                run: |
                    bazelisk query 'kind(kt_jvm_test, ...)' --output label > /tmp/targets
            -   name: Bazel test
                uses: ./.github/actions/bazel
                with:
                    bazel-command: test --target_pattern_file=/tmp/targets
                    cache-key: bazel-test

    bazel-android-lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Bazel Android Lint
                uses: ./.github/actions/bazel
                with:
                    bazel-command: test //sample-android:sample-android-demo-free-debug.lint_test
                    cache-key: bazel-lint

    grazel-build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: "zulu"
                    java-version: "17"
            -   uses: burrunan/gradle-cache-action@v1.12
                name: grazel-build
                with:
                    debug: false
                    job-id: grazel-build
                    read-only: ${{ github.ref != 'refs/heads/master' }}
                    gradle-dependencies-cache-key: |
                        gradle/libs.versions.toml
                    arguments: assembleDebug --scan

    grazel-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: "zulu"
                    java-version: "17"
            -   uses: burrunan/gradle-cache-action@v1.12
                name: grazel-test
                with:
                    debug: false
                    job-id: grazel-test
                    read-only: ${{ github.ref != 'refs/heads/master' }}
                    gradle-dependencies-cache-key: |
                        gradle/libs.versions.toml
                    arguments: test --scan

    grazel-gradle-plugin-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: "zulu"
                    java-version: "17"
            -   uses: burrunan/gradle-cache-action@v1.12
                name: grazel-gradle-plugin-test
                with:
                    debug: false
                    job-id: grazel-gradle-plugin-test
                    build-root-directory: grazel-gradle-plugin
                    read-only: ${{ github.ref != 'refs/heads/master' }}
                    gradle-dependencies-cache-key: |
                        gradle/libs.versions.toml
                    arguments: test --scan

    migrate-to-bazel-validation:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Bazelisk
                uses: bazelbuild/setup-bazelisk@v2
            -   name: Install JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: "zulu"
                    java-version: "17"
            -   uses: burrunan/gradle-cache-action@v1.12
                name: migrate-to-bazel-validation
                with:
                    debug: false
                    job-id: migrate-to-bazel-validation
                    read-only: ${{ github.ref != 'refs/heads/master' }}
                    gradle-dependencies-cache-key: |
                        gradle/libs.versions.toml
                    arguments: migrateToBazel --scan